package Cliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alejandro
 */
import java.util.List;
import Common.InfoHorno;
import Common.InfoAlmacen;
import Common.InterfazObjetoRemoto;
import Server.Repostero;
import java.awt.Color;
import java.awt.Image;
import java.rmi.ConnectException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class ClienteUI extends javax.swing.JFrame implements Runnable{

    // Declaración de las listas
    private List<Repostero> listaReposteros;
    private List<InfoHorno> listaHornos;
    private InfoAlmacen almacen;
    private InterfazObjetoRemoto objetoRemoto;
    public ClienteUI(InterfazObjetoRemoto objetoRemoto) throws RemoteException{
        initComponents();
        this.objetoRemoto=objetoRemoto;
        this.listaReposteros=objetoRemoto.getInfoReposteros();
        this.listaHornos=objetoRemoto.getInfoHornos();
        this.almacen=objetoRemoto.getInfoAlmacen();
        this.getContentPane().setBackground(new Color(239, 227, 215));
        // Cargar la primera imagen
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/deco7.png"));
        Image img1 = icon1.getImage(); // Convierte la imagen a tipo Image
        Image resizedImg1 = img1.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
        icon1 = new ImageIcon(resizedImg1); // Asignar la imagen redimensionada
        jLabel15.setIcon(icon1); // Establecer la imagen en el JLabel

        
        icon1 = new ImageIcon(getClass().getResource("/images/deco4.png"));
        img1 = icon1.getImage(); // Convierte la imagen a tipo Image
        resizedImg1 = img1.getScaledInstance(jLabel14.getWidth(), jLabel14.getHeight(), Image.SCALE_SMOOTH);
        icon1 = new ImageIcon(resizedImg1); // Asignar la imagen redimensionada
        jLabel14.setIcon(icon1); // Establecer la imagen en el JLabel
        
        icon1 = new ImageIcon(getClass().getResource("/images/logo.png"));
        img1 = icon1.getImage(); // Convierte la imagen a tipo Image
        resizedImg1 = img1.getScaledInstance(jLabel16.getWidth(), jLabel16.getHeight(), Image.SCALE_SMOOTH);
        icon1 = new ImageIcon(resizedImg1); // Asignar la imagen redimensionada
        jLabel16.setIcon(icon1); // Establecer la imagen en el JLabel


    }
    public void update() throws RemoteException{
        listaReposteros = objetoRemoto.getInfoReposteros();
        listaHornos = objetoRemoto.getInfoHornos();
        almacen = objetoRemoto.getInfoAlmacen();
        updateReposteros();
        updateHornos();
        updateAlmacen();
    }
    public void updateReposteros(){
        JTextField[] listaGalletasGeneradasFields = {r1ngg,r2ngg,r3ngg,r4ngg,r5ngg};
        JTextField[] listaGalletasDesperdiciadasFields ={r1ngd,r2ngd,r3ngd,r4ngd,r5ngd};
        for(int i=0;i<listaReposteros.size();i++){
            int galletasGeneradas=listaReposteros.get(i).getnGalletasGeneradasTotales();
            listaGalletasGeneradasFields[i].setText(""+galletasGeneradas);
            int galletasDesperdiciadas=listaReposteros.get(i).getnGalletasDesperdiciadasTotales();
            listaGalletasDesperdiciadasFields[i].setText(""+galletasDesperdiciadas);
        }
    }
    public void updateHornos() {
        // Definir los campos de texto para los hornos
        JTextField[] hornosGalletasHorneadasFields = {h1gh, h2gh, h3gh}; // Para galletas horneadas
        JTextField[] horneandoFields={jTextField1,jTextField2,jTextField3};
        // Recorrer los hornos y actualizar los valores
        for (int i = 0; i < listaHornos.size(); i++) {
            InfoHorno horno = listaHornos.get(i);

            // Actualizar los campos con los valores de InfoHorno
            hornosGalletasHorneadasFields[i].setText("" + horno.galletasHorneadas());
            if(horno.horneando()){
                horneandoFields[i].setBackground(Color.RED);
            }
            else{
                horneandoFields[i].setBackground(Color.WHITE);
            }
        }
    }
    public void updateAlmacen() {
        // Actualizar los campos de texto para galletas almacenadas y consumidas
        aga.setText("" + almacen.nGalletasAlmacenadas());
        agc.setText("" + almacen.nGalletasConsumidas());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nGalletasGeneradasLabel = new javax.swing.JLabel();
        nGalletasDesperdiciadasLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r1ngg = new javax.swing.JTextField();
        r1ngd = new javax.swing.JTextField();
        r2ngg = new javax.swing.JTextField();
        r2ngd = new javax.swing.JTextField();
        r3ngg = new javax.swing.JTextField();
        r3ngd = new javax.swing.JTextField();
        r4ngg = new javax.swing.JTextField();
        r4ngd = new javax.swing.JTextField();
        r5ngg = new javax.swing.JTextField();
        r5ngd = new javax.swing.JTextField();
        buttonR1 = new javax.swing.JToggleButton();
        buttonR2 = new javax.swing.JToggleButton();
        buttonR3 = new javax.swing.JToggleButton();
        buttonR4 = new javax.swing.JToggleButton();
        buttonR5 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        h1gh = new javax.swing.JTextField();
        h2gh = new javax.swing.JTextField();
        h3gh = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        aga = new javax.swing.JTextField();
        agc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(920, 720));
        setMinimumSize(new java.awt.Dimension(920, 720));
        setPreferredSize(new java.awt.Dimension(920, 720));
        setResizable(false);

        nGalletasGeneradasLabel.setText("Galletas generadas");

        nGalletasDesperdiciadasLabel.setText("Galletas desperdiciadas");

        jLabel1.setText("Repostero 1");

        jLabel2.setText("Repostero 2");

        jLabel3.setText("Repostero 3");

        jLabel4.setText("Repostero 4");

        jLabel5.setText("Repostero 5");

        r1ngg.setText("jTextField1");

        r1ngd.setText("jTextField2");

        r2ngg.setText("jTextField1");

        r2ngd.setText("jTextField2");

        r3ngg.setText("jTextField1");

        r3ngd.setText("jTextField2");

        r4ngg.setText("jTextField1");

        r4ngd.setText("jTextField2");

        r5ngg.setText("jTextField1");

        r5ngd.setText("jTextField2");

        buttonR1.setText("parar");
        buttonR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR1ActionPerformed(evt);
            }
        });

        buttonR2.setText("parar");
        buttonR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR2ActionPerformed(evt);
            }
        });

        buttonR3.setText("parar");
        buttonR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR3ActionPerformed(evt);
            }
        });

        buttonR4.setText("parar");
        buttonR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR4ActionPerformed(evt);
            }
        });

        buttonR5.setText("parar");
        buttonR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonR5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Galletas horneadas");

        jLabel7.setText("Horneando");

        jLabel8.setText("Horno 1");

        jLabel9.setText("Horno 2");

        jLabel10.setText("Horno 3");

        h1gh.setText("jTextField1");
        h1gh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ghActionPerformed(evt);
            }
        });

        h2gh.setText("jTextField1");
        h2gh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ghActionPerformed(evt);
            }
        });

        h3gh.setText("jTextField1");

        jLabel11.setText("Galletas almacenadas");

        jLabel12.setText("Galletas consumidas");

        jLabel13.setText("Almacén");

        aga.setText("jTextField4");

        agc.setText("jTextField4");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(r5ngg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonR1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonR2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonR3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(buttonR5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonR4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(nGalletasGeneradasLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(r1ngg, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(r2ngg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(54, 54, 54)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(r1ngd)
                                                    .addComponent(nGalletasDesperdiciadasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(r2ngd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(r4ngg)
                                                    .addComponent(r3ngg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(54, 54, 54)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(r3ngd, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(r4ngd)
                                                    .addComponent(r5ngd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(129, 129, 129)))
                                .addGap(55, 55, 55)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(aga, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(305, 305, 305)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(agc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel10))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(h1gh)
                                    .addComponent(h2gh)
                                    .addComponent(h3gh))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nGalletasGeneradasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(r1ngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(r2ngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(nGalletasDesperdiciadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r1ngd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(r2ngd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(r3ngd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r3ngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(r4ngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(r4ngd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r5ngd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(r5ngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonR1)
                                .addGap(17, 17, 17)
                                .addComponent(buttonR2)
                                .addGap(18, 18, 18)
                                .addComponent(buttonR3)
                                .addGap(18, 18, 18)
                                .addComponent(buttonR5)
                                .addGap(18, 18, 18)
                                .addComponent(buttonR4)))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(h1gh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(h2gh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(h3gh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(aga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(agc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(75, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR1ActionPerformed
    try {
        Repostero repostero = listaReposteros.get(0); // Obtener el repostero correspondiente
        
        if (buttonR1.isSelected()) { 
            // Si el botón está en estado "seleccionado" (true)
            objetoRemoto.pararRepostero(0); // Pausar el repostero
            buttonR1.setText("Reanudar"); // Cambiar el texto a "Reanudar"
        } else { 
            // Si el botón está en estado "no seleccionado" (false)
            objetoRemoto.reanudarRepostero(0); // Reanudar el repostero
            buttonR1.setText("Parar"); // Cambiar el texto a "Parar"
        }
    } catch (Exception e) {
        e.printStackTrace(); // Manejo de excepciones
        }
    }//GEN-LAST:event_buttonR1ActionPerformed

    private void buttonR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR2ActionPerformed
        try {
        Repostero repostero = listaReposteros.get(1); // Obtener el repostero correspondiente al botón R5

        if (buttonR2.isSelected()) { 
            // Si el botón está en estado "seleccionado" (true)
            objetoRemoto.pararRepostero(1); // Pausar el repostero
            buttonR2.setText("Reanudar"); // Cambiar el texto a "Reanudar"
        } else { 
            // Si el botón está en estado "no seleccionado" (false)
            objetoRemoto.reanudarRepostero(1); // Reanudar el repostero
            buttonR2.setText("Parar"); // Cambiar el texto a "Parar"
        }
    } catch (Exception e) {
        e.printStackTrace(); // Manejo de excepciones
    }
    }//GEN-LAST:event_buttonR2ActionPerformed

    private void buttonR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR3ActionPerformed
       try {
        Repostero repostero = listaReposteros.get(2); // Obtener el repostero correspondiente al botón R3

        if (buttonR3.isSelected()) { 
            // Si el botón está en estado "seleccionado" (true)
            objetoRemoto.pararRepostero(2); // Pausar el repostero
            buttonR3.setText("Reanudar"); // Cambiar el texto a "Reanudar"
        } else { 
            // Si el botón está en estado "no seleccionado" (false)
            objetoRemoto.reanudarRepostero(2); // Reanudar el repostero
            buttonR3.setText("Parar"); // Cambiar el texto a "Parar"
        }
    } catch (Exception e) {
        e.printStackTrace(); // Manejo de excepciones
    }
    }//GEN-LAST:event_buttonR3ActionPerformed

    private void buttonR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR4ActionPerformed
        try {
        Repostero repostero = listaReposteros.get(3); // Obtener el repostero correspondiente al botón R4

        if (buttonR4.isSelected()) { 
            // Si el botón está en estado "seleccionado" (true)
            objetoRemoto.pararRepostero(3); // Pausar el repostero
            buttonR4.setText("Reanudar"); // Cambiar el texto a "Reanudar"
        } else { 
            // Si el botón está en estado "no seleccionado" (false)
            objetoRemoto.reanudarRepostero(3); // Reanudar el repostero
            buttonR4.setText("Parar"); // Cambiar el texto a "Parar"
        }
    } catch (Exception e) {
        e.printStackTrace(); // Manejo de excepciones
    }
    }//GEN-LAST:event_buttonR4ActionPerformed

    private void buttonR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonR5ActionPerformed
        try {
        Repostero repostero = listaReposteros.get(4); // Obtener el repostero correspondiente al botón R5

        if (buttonR5.isSelected()) { 
            // Si el botón está en estado "seleccionado" (true)
            objetoRemoto.pararRepostero(4); // Pausar el repostero
            buttonR5.setText("Reanudar"); // Cambiar el texto a "Reanudar"
        } else { 
            // Si el botón está en estado "no seleccionado" (false)
            objetoRemoto.reanudarRepostero(4); // Reanudar el repostero
            buttonR5.setText("Parar"); // Cambiar el texto a "Parar"
        }
    } catch (Exception e) {
        e.printStackTrace(); // Manejo de excepciones
    }
    }//GEN-LAST:event_buttonR5ActionPerformed

    private void h1ghActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ghActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1ghActionPerformed

    private void h2ghActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ghActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2ghActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ClienteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aga;
    private javax.swing.JTextField agc;
    private javax.swing.JToggleButton buttonR1;
    private javax.swing.JToggleButton buttonR2;
    private javax.swing.JToggleButton buttonR3;
    private javax.swing.JToggleButton buttonR4;
    private javax.swing.JToggleButton buttonR5;
    private javax.swing.JTextField h1gh;
    private javax.swing.JTextField h2gh;
    private javax.swing.JTextField h3gh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nGalletasDesperdiciadasLabel;
    private javax.swing.JLabel nGalletasGeneradasLabel;
    private javax.swing.JTextField r1ngd;
    private javax.swing.JTextField r1ngg;
    private javax.swing.JTextField r2ngd;
    private javax.swing.JTextField r2ngg;
    private javax.swing.JTextField r3ngd;
    private javax.swing.JTextField r3ngg;
    private javax.swing.JTextField r4ngd;
    private javax.swing.JTextField r4ngg;
    private javax.swing.JTextField r5ngd;
    private javax.swing.JTextField r5ngg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //System.out.println("--------------------------------COMIENZA EL RUNEO-------------------------------------");
        while (true) {
            try {
                update();
                Thread.sleep(100); // Pausa para evitar saturar la memoria
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ConnectException ce) {
                // Mostrar el mensaje de error
                JOptionPane.showMessageDialog(null, 
                    "Se ha desconectado el servidor. Intente nuevamente más tarde.", 
                    "Error de Conexión", 
                    JOptionPane.ERROR_MESSAGE);

                // Cerrar la ventana (dispose)
                dispose();

                // Finalizar el programa (si es necesario)
                System.exit(0);

                ce.printStackTrace();
            } catch (RemoteException ex) {
                Logger.getLogger(ClienteUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}